### ISSUE TITLE
Алгоритм создания курса и контеста в нём

### ISSUE THREAD

**Issue by shestimerov** [InformaticsMskRu/informatics-mccme-ru#129]
Сделать краткий ман (который можно выложить пользователям) по тому как с этим работать и список улучшений по ui

**Comment by Pavel-Osipov** [comment]
Done. Написано в начерно сверстано.
Чистовая верстка будет, когда будет понятно в какой именно раздел сайта мы хотим это положить (надо будет правильно загрузить картинки и поправить пути).
Пусть будет 8 рабочих часов.

**Comment by Pavel-Osipov** [comment]
Да, тикет закрываю.
