### ISSUE TITLE
Битые ссылки - ЕГЭ

### ISSUE THREAD

**Issue by Pavel-Osipov** [InformaticsMskRu/informatics-mccme-ru#152]
Вот в этом разделе.
http://informatics.mccme.ru/course/view.php?id=77
Может стоит его вообще прикрыть? Он же дохлый. Не?

**Comment by shestimerov** [comment]
Если тут нет ничего полезного то давай закрывать

**Comment by Pavel-Osipov** [comment]
Думаю можно закрыть вообще. Лично у меня нет желания поддерживать это в актуальном состоянии.
