### ISSUE TITLE
тесты

### ISSUE THREAD

**Issue by shestimerov** [InformaticsMskRu/informatics-mccme-ru#270]
Даниил, [30 авг. 2018 г., 19:35:46]:
Добрый вечер. Кажется в задаче 2598 тест 13 некорректен. Из условия следует, что в данном тесте должна быть возможность добраться из вершины 1 в вершину 2, а это не так.

Хотя данная ошибка и не влияет на прохождение или непрохождние решений

**Comment by damm1t** [comment]
могу исправить

**Comment by damm1t** [comment]
done
