### ISSUE TITLE
Переехать на гитхаб

### ISSUE THREAD

**Issue by GoogleCodeExporter** [InformaticsMskRu/informatics-mccme-ru#61]
```
В связи с закрытием сервиса 25 января 2016 года
```

Original issue reported on code.google.com by `gurovic@gmail.com` on 12 Mar 2015 at 6:17

**Comment by shestimerov** [comment]
Переехали, только wiki по курсам не переехало, надо перенести руками

**Comment by shestimerov** [comment]
забить
