### ISSUE TITLE
Не работает reload

### ISSUE THREAD

**Issue by asukaev** [InformaticsMskRu/informatics-mccme-ru#78]
Reload doesn't work.
http://informatics.mccme.ru/py/contest/ejudge/reload/2118
http://informatics.mccme.ru/py/contest/ejudge/reload/2119
http://informatics.mccme.ru/py/contest/ejudge/reload/2120
http://informatics.mccme.ru/py/contest/ejudge/reload/2121

Internal Server Error
The server encountered an internal error or misconfiguration and was unable to complete your request.

Please contact the server administrator, webmaster@localhost and inform them of the time the error occurred, and anything you might have done that may have caused the error.

More information about this error may be available in the server error log.

**Comment by shestimerov** [comment]
пропал autoincrement в табличке mdl_ejudge_contest, поправил
Слава, проверь что у тебя клонирование контеста не поломалось

**Comment by shestimerov** [comment]
@feldsherov расскажи в чем там проблемы с кодировкой?

**Comment by feldsherov** [comment]
Все хорошо, clone заработал.
