### ISSUE TITLE
Материалы по теме "Игры"

### ISSUE THREAD

**Issue by malyshkaterina** [InformaticsMskRu/informatics-mccme-ru#81]
В разделе http://informatics.mccme.ru/course/view.php?id=30 нужно:
1) Исправить теоретические материалы – вставить картинки, расписать теорию чуть подробнее
2) Добавить задач (если на информатиксе какие-то есть) 
3) Изучить  возможность прикрутить гитхабовский шаблонизатор (чтобы страница с теорией выглядела вот так https://github.com/hseos/hseos-course/tree/master/18-thread)

**Comment by feach** [comment]
1) и 2) - done.

**Comment by feach** [comment]
Закрываю до решения по CSS.
