### ISSUE TITLE
Написать теорию в "Разборе выражений" и "ГМО" 

### ISSUE THREAD

**Issue by malyshkaterina** [InformaticsMskRu/informatics-mccme-ru#89]
Разбор выражений сейчас без теории: http://informatics.mccme.ru/course/view.php?id=84
В глобальных методах оптимизации может быть попробовать что-то кроме отжига использовать? Не знаю, разумно ли давать детям какой-нибудь градиентный спуск http://informatics.mccme.ru/course/view.php?id=93

**Comment by feach** [comment]
Done частично.
В теме "Разбор выражений" выложил древнюю статью Матюхина в pdf-ке.
Плюс, добавил некоторое количество более простых примеров на сишнике.

По методам оптимизации - вопрос к обсуждению. Там така-а-а-а-а-ая математика. :(
Разумно выглядит классический подход, типа "координатный спуск" -> "градиентный спуск" -> "отжиг". Но это курс приличной толщины + задачки. Оно того в принципе стоит?
Ибо градиентный спуск - это как минимум словеса про сходимость, и оно как-то ненавязчиво начинает тянуть за собой разные куски теории... :)

**Comment by feach** [comment]
Теория расписана.
В Методах глобальной оптимизации создал отдельный раздел с "постановкой задачи". Это "на вырост", если потом руки дойдут написать про генетические алгоритмы.
Отжиг описал.
Закрываю тикет.
