### ISSUE TITLE
Дерево на главной - тестирование под разными браузерами

### ISSUE THREAD

**Issue by GoogleCodeExporter** [InformaticsMskRu/informatics-mccme-ru#9]
```
Не работает в safari на маке и во встроенном 
браузере андроида
```

Original issue reported on code.google.com by `vran...@gmail.com` on 27 Mar 2014 at 5:47

**Comment by feach** [comment]
Safari 5.1.4. - дерево работает.
Opera/FF/IE дерево работает.
Встроенный браузер Android 4 - дерево работает.
Что еще потестировать?

p.s. Попутно в левой колонке найдена ссылка "Как работать на сайте" ведущая в документ Word. 

Предлагаю либо переверстать, либо перенести материал в FAQ.
Там же рядом ссылка "Ввод-вывод на Java", предлагаю убить.

Под свежепоставленным Safari, кстати (на cookie не кивать :) ) наблюдаю постороннюю хрень что в констесте, что в задаче
https://yadi.sk/i/xPY_Cnph3EZTZo
https://yadi.sk/i/292UwwCc3EZTaC
Это лечится?
