### ISSUE TITLE
Страница с разными особенностями языка.

### ISSUE THREAD

**Issue by shestimerov** [InformaticsMskRu/informatics-mccme-ru#95]
По некоторым языкам есть часто-встречаемы проблемы со сдачей, например в java нельзя сдавать класс, который содержится в каком-то пакете:
package new1;

import java.util.Scanner;

public class Main {

	public static void main(String[] args) {
		Scanner in = new Scanner(System.in);
        int a = in.nextInt();
        //int b = in.nextInt();
        System.out.println("The next number for the number "+a+" is "+(a+1)+".");
        System.out.println("The previous number for the number "+a+" is "+(a-1)+".");
        in.close();
	}

}

2088-119737	Han Black	113051. Следующее и предыдущее

Надо сделать общую страницу где по каждому языку можно размещать faq.

Придумать как оформить (например, bootstap список языков c разворотом когда кликаем по языку)

Можно придумать скриптик, который еще говорит актуальные версии компиляторов.

Сделать примеры задачи a+b на всех поддерживаемых языках.

**Comment by feach** [comment]
Сделано, выложено на место старого FAQ. 
Для красоты осталось выложить на Github и прикрутить скриптом, но это потом. 
Закрываю тикет. Будем считать, что 5 часов.
