### ISSUE TITLE
Проверить работу антиробота

### ISSUE THREAD

**Issue by shestimerov** [InformaticsMskRu/informatics-mccme-ru#96]
Надо понять какая версия антиробота стоит на регистрации, какие у нее есть артефакты и можно ли ее обойти.

**Comment by feach** [comment]
Ну-у-у. Тривиальный вариант - кто-то заюзал на сайте свой код, а не стал регистерить новый. Или чей-то google.account сломался и там убрали галочку настройки.
Domain Name Validation | reCAPTCHA .. developers.google.com
Как все понимают, проверить это сам я не могу, ибо не знаю чей это акк изначально.

Добавки, которые на мой взгляд не лишне сделать:
1. добавить проверку hostname в тест captcha, сейчас проверяется только удачно/нет.
2. ну, еще можно в начале страницы нагло проверять user-agent и прочие интересные данные сессии (IP), и если они нам не нравятся - закрывать ее нафиг.

Кстати, не вижу самую тривиальную проверку. Типа "если страница открыта не нашим движком, то die() без сообщений".

Что из этого тестим/реализуем?

**Comment by feach** [comment]
Есть предложение - закрыть тикет как "более организационный, чем технический".

**Comment by feach** [comment]
Как вариант - создавать логин ejudge в момент первого сабмита, а не сразу. Но это - деталька не от этого тикета. Закрываю, 4 часа.
